piControl: Add Tests and Jobs [REVPI-2542]
RevolutionPi/LAVA-test-definitions pull request #9
Opened 2022-09-02 06:54 UTC by RamiGspo

Test pi Control - Check picontrol driver and picontrol0 device

2022-09-06 12:56 UTC, ferdrich-kunbus requested changes

2022-09-06 12:56 UTC, ferdrich-kunbus commented on automated/linux/picontrol/test-pc-1.yaml
> +    name: Test usb-1
Should be pc-1

2022-09-06 20:36 UTC, RamiGspo commented on automated/linux/picontrol/test-pc-1.yaml
> +    name: Test usb-1
Thank you. I have updated it.

2022-09-09 12:58 UTC, ferdrich-kunbus approved these changes
ok

2022-09-09 14:34 UTC, merged